### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by aaronroberson** [TheNodeILs/formage#128]
running formage@3.2.21 with mongoose@4.1.6 and express@4 I get the following error:
```
/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/forms/AdminForm.js:40
        throw e;
              ^
TypeError: undefined is not a function
    at ArraySubForm.SubForm (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/forms/SubForm.js:12:19)
    at new ArraySubForm (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/forms/ArraySubForm.js:8:13)
    at new ArrayField (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/forms/ArrayField.js:17:26)
    at path_to_field (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/adapters/mongoose.js:159:16)
    at /Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/adapters/mongoose.js:63:21
    at /Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:3513:29
    at forOwn (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.map (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:3512:9)
    at lodash.ctor.(anonymous function) [as map] (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:5924:31)
    at paths_to_fields (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/adapters/mongoose.js:62:21)
    at Function.getFields (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/adapters/mongoose.js:54:18)
    at Function.AdminForm.buildFieldsHierarchy (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/forms/AdminForm.js:36:36)
    at /Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/lib/registry.js:42:35
    at /Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:3513:29
    at forOwn (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.map (/Users/aaronroberson/Sites/gsn/draft4-server-admin/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/dist/lodash.js:3512:9)```

**Comment by aaronroberson** [comment]
Has this project been abandoned?

**Comment by refack** [comment]
I'm back.
Can you post the model and a sample code?
